In [1]:
from db_manager import DBManager
from game_editor import GameEditor
import pandas as pd

In [42]:
db = DBManager()
table_game = db.table_to_dataframe(table_name='table_game')
db.close()
table_game.head()

✅ Connexion établie : database/databeach_base.db
✅ Table 'table_game' exportée : 16 lignes, 12 colonnes
🔒 Connexion fermée.

,GAME_ID,serie,stage,teamA,teamB,victoire,set1_score,set2_score,set3_score,set1_score_adv,set2_score_adv,set3_score_adv
0,JOMR_jan26_MBV_01,MBV_S2-250_F_jan26,poule,JOMR,NoG_AliP,JOMR,,,,,,
1,JOMR_jan26_MBV_02,MBV_S2-250_F_jan26,poule,JOMR,AleN_EmP,JOMR,,,,,,
2,JOMR_jan26_MBV_03,MBV_S2-250_F_jan26,demi,JOMR,PauG_NeCH,JOMR,,,,,,
3,JOMR_jan26_MBV_04,MBV_S2-250_F_jan26,finale,JOMR,AleM_LauA,AleM_LauA,,,,,,
4,JOMR_nov24_Leuven_01,Leuven_Int_F_nov24,barrage,JOMR,(adv),(adv),,,,,,

In [ ]:
from db_manager import DBManager
import pprint

serie_id = 'MBV_S2-250_F_jan26'
team_serving = 'JOMR'

with DBManager() as db:
    db.cursor.execute(
        f"""SELECT POINT_ID, Service_side 
        FROM table_points
        WHERE game_id IN
            (SELECT GAME_ID
            FROM table_game
            WHERE serie = ?)
        AND Service_side = ?""",
        (serie_id,team_serving)
    )
    
POINTS_IDS = [row[0] for row in db.cursor.fetchall()]
# print(f"POINTS_IDS for serie_id '{serie_id}' and team_serving '{team_serving}': {POINTS_IDS}")
POUNTS_IDS_STR = ', '.join(map(str, POINTS_IDS))
print(f"POINTS_IDS for serie_id '{serie_id}' and team_serving '{team_serving}': {POUNTS_IDS_STR}")


#     db.cursor.execute(
#         """
#         SELECT GAME_ID, serie
#         FROM table_game
#         WHERE serie = ?""",
#         (serie_id,)
# )
    # GAME_IDS_IDS = [row[0] for row in db.cursor.fetchall()]
    # print(f"GAME_IDS for serie_id '{serie_id}': {GAME_IDS_IDS}")

✅ Connexion établie : database/databeach_base.db
POINTS_IDS for serie_id 'MBV_S2-250_F_jan26' and team_serving 'JOMR': JOMR_jan26_MBV_01_p2, JOMR_jan26_MBV_01_p5, JOMR_jan26_MBV_01_p7, JOMR_jan26_MBV_01_p8, JOMR_jan26_MBV_01_p9, JOMR_jan26_MBV_01_p10, JOMR_jan26_MBV_01_p12, JOMR_jan26_MBV_01_p13, JOMR_jan26_MBV_01_p14, JOMR_jan26_MBV_01_p16, JOMR_jan26_MBV_01_p19, JOMR_jan26_MBV_01_p20, JOMR_jan26_MBV_01_p22, JOMR_jan26_MBV_01_p23, JOMR_jan26_MBV_01_p25, JOMR_jan26_MBV_01_p26, JOMR_jan26_MBV_01_p27, JOMR_jan26_MBV_01_p30, JOMR_jan26_MBV_01_p31, JOMR_jan26_MBV_01_p33, JOMR_jan26_MBV_02_p2, JOMR_jan26_MBV_02_p3, JOMR_jan26_MBV_02_p5, JOMR_jan26_MBV_02_p7, JOMR_jan26_MBV_02_p12, JOMR_jan26_MBV_02_p15, JOMR_jan26_MBV_02_p16, JOMR_jan26_MBV_02_p18, JOMR_jan26_MBV_02_p19, JOMR_jan26_MBV_02_p20, JOMR_jan26_MBV_02_p23, JOMR_jan26_MBV_02_p24, JOMR_jan26_MBV_02_p26, JOMR_jan26_MBV_02_p28, JOMR_jan26_MBV_02_p30, JOMR_jan26_MBV_02_p31, JOMR_jan26_MBV_02_p34, JOMR_jan26_MBV_03_p3, JOMR_jan26_MBV_03_p4, JOMR_jan26_MBV_03_p5, JOMR_jan26_MBV_03_p6, JOMR_jan26_MBV_03_p7, JOMR_jan26_MBV_03_p9, JOMR_jan26_MBV_03_p10, JOMR_jan26_MBV_03_p16, JOMR_jan26_MBV_03_p19, JOMR_jan26_MBV_03_p25, JOMR_jan26_MBV_03_p26, JOMR_jan26_MBV_03_p27, JOMR_jan26_MBV_03_p28, JOMR_jan26_MBV_03_p29, JOMR_jan26_MBV_03_p30, JOMR_jan26_MBV_03_p31, JOMR_jan26_MBV_03_p34, JOMR_jan26_MBV_03_p35, JOMR_jan26_MBV_03_p37, JOMR_jan26_MBV_03_p38, JOMR_jan26_MBV_03_p40, JOMR_jan26_MBV_03_p43, JOMR_jan26_MBV_03_p45, JOMR_jan26_MBV_03_p51, JOMR_jan26_MBV_03_p52, JOMR_jan26_MBV_03_p53, JOMR_jan26_MBV_03_p56, JOMR_jan26_MBV_03_p58, JOMR_jan26_MBV_03_p60, JOMR_jan26_MBV_03_p62, JOMR_jan26_MBV_03_p63, JOMR_jan26_MBV_03_p65, JOMR_jan26_MBV_03_p67, JOMR_jan26_MBV_03_p68, JOMR_jan26_MBV_03_p70, JOMR_jan26_MBV_04_p1, JOMR_jan26_MBV_04_p5, JOMR_jan26_MBV_04_p6, JOMR_jan26_MBV_04_p10, JOMR_jan26_MBV_04_p13, JOMR_jan26_MBV_04_p17, JOMR_jan26_MBV_04_p21, JOMR_jan26_MBV_04_p22, JOMR_jan26_MBV_04_p24, JOMR_jan26_MBV_04_p25, JOMR_jan26_MBV_04_p26, JOMR_jan26_MBV_04_p33, JOMR_jan26_MBV_04_p34, JOMR_jan26_MBV_04_p40, JOMR_jan26_MBV_04_p43
🔒 Connexion fermée.

In [6]:
table_points

,POINT_ID,Service_side,team_a_score,team_b_score,team_a_sets,team_b_sets,team_a_score_diff,team_b_score_diff,point_winner,game_id
0,JOMR_nov25_MBV_03_p1,VerF_FloA,0,0,0,0,0,0,JOMR,JOMR_nov25_MBV_03
1,JOMR_nov25_MBV_03_p2,JOMR,1,0,0,0,1,-1,JOMR,JOMR_nov25_MBV_03
2,JOMR_nov25_MBV_03_p3,JOMR,2,0,0,0,2,-2,VerF_FloA,JOMR_nov25_MBV_03
3,JOMR_nov25_MBV_03_p4,VerF_FloA,2,1,0,0,1,-1,VerF_FloA,JOMR_nov25_MBV_03
4,JOMR_nov25_MBV_03_p5,VerF_FloA,2,2,0,0,0,0,JOMR,JOMR_nov25_MBV_03
...,...,...,...,...,...,...,...,...,...,...
787,JOMR_oct25_SSA_05_p96,MaMeB_MarS,12,10,1,1,2,-2,MaMeB_MarS,JOMR_oct25_SSA_05
788,JOMR_oct25_SSA_05_p97,MaMeB_MarS,12,11,1,1,1,-1,JOMR,JOMR_oct25_SSA_05
789,JOMR_oct25_SSA_05_p98,JOMR,13,11,1,1,2,-2,MaMeB_MarS,JOMR_oct25_SSA_05
790,JOMR_oct25_SSA_05_p99,MaMeB_MarS,13,12,1,1,1,-1,JOMR,JOMR_oct25_SSA_05
791,JOMR_oct25_SSA_05_p100,JOMR,14,12,1,1,2,-2,JOMR,JOMR_oct25_SSA_05

In [ ]:
db.execute_query(
    f"""ArithmeticError
    """
)

In [13]:
points_ids