In [1]:
from db_manager import DBManager
from game_editor import GameEditor
import pandas as pd

In [4]:
paire_id = 'JOMR'
from db_manager import DBManager
db = DBManager()
db.cursor.execute(
    """SELECT Name_joueurA, Name_joueurB
    FROM table_players
    WHERE PAIRE_ID = ?""",
    (paire_id,)
)
result = db.cursor.fetchone()
if result: 
    player_a, player_b = result
    print(f"Player A: {player_a}, Player B: {player_b}")

from video_edit_utils import basic_action_grader

dict_b = basic_action_grader(
    video_path=r'C:\Users\habib\Desktop\Montages volley et beach\Jade&Math\matchs preprocess\points_segmented\JOMR_jan26_MBV_01_p1.mp4',
    player_a=player_a,
    player_b=player_b,
    action_to_grade='pass'
)

✅ Connexion établie : database/databeach_base.db
Player A: OFFREDI Jade, Player B: RANC Mathilde

In [5]:
dict_b

{'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'error'}

In [5]:
list_grades_BSD_02 = [{'point_id': 'JOMR_nov25_BSD_02_p2', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p6', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'undetermined'}, {'point_id': 'JOMR_nov25_BSD_02_p10', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p15', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p17', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p20', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'perfect pass'}, {'point_id': 'JOMR_nov25_BSD_02_p21', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p23', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p25', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'perfect pass'}, {'point_id': 'JOMR_nov25_BSD_02_p26', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'out-of-system pass'}, {'point_id': 'JOMR_nov25_BSD_02_p32', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p40', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'error'}, {'point_id': 'JOMR_nov25_BSD_02_p41', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}]

In [7]:
import json

with open('list_grades_BSD_02.json', 'w') as f:
    json.dump(list_grades_BSD_02, f, indent=2)

In [6]:
import pprint
import pandas
# pprint.pprint(list_grades)
df = pandas.DataFrame(list_grades_BSD_02)
df

                 point_id         player action               grade
0    JOMR_nov25_BSD_02_p2  RANC Mathilde   pass        average pass
1    JOMR_nov25_BSD_02_p6   OFFREDI Jade   pass        undetermined
2   JOMR_nov25_BSD_02_p10  RANC Mathilde   pass        average pass
3   JOMR_nov25_BSD_02_p15   OFFREDI Jade   pass        average pass
4   JOMR_nov25_BSD_02_p17   OFFREDI Jade   pass        average pass
5   JOMR_nov25_BSD_02_p20  RANC Mathilde   pass        perfect pass
6   JOMR_nov25_BSD_02_p21   OFFREDI Jade   pass        average pass
7   JOMR_nov25_BSD_02_p23   OFFREDI Jade   pass        average pass
8   JOMR_nov25_BSD_02_p25   OFFREDI Jade   pass        perfect pass
9   JOMR_nov25_BSD_02_p26   OFFREDI Jade   pass  out-of-system pass
10  JOMR_nov25_BSD_02_p32  RANC Mathilde   pass        average pass
11  JOMR_nov25_BSD_02_p40  RANC Mathilde   pass               error
12  JOMR_nov25_BSD_02_p41   OFFREDI Jade   pass        average pass

In [3]:
from db_manager import DBManager
db = DBManager()
db.list_all_tables()
db.table_to_dataframe('table_points')

✅ Connexion établie : database/databeach_base.db
📋 Tables disponibles : ['table_game', 'table_players', 'table_points', 'table_serie']
✅ Table 'table_points' exportée : 792 lignes, 10 colonnes

,POINT_ID,Service_side,team_a_score,team_b_score,team_a_sets,team_b_sets,team_a_score_diff,team_b_score_diff,point_winner,game_id
0,JOMR_nov25_MBV_03_p1,VerF_FloA,0,0,0,0,0,0,JOMR,JOMR_nov25_MBV_03
1,JOMR_nov25_MBV_03_p2,JOMR,1,0,0,0,1,-1,JOMR,JOMR_nov25_MBV_03
2,JOMR_nov25_MBV_03_p3,JOMR,2,0,0,0,2,-2,VerF_FloA,JOMR_nov25_MBV_03
3,JOMR_nov25_MBV_03_p4,VerF_FloA,2,1,0,0,1,-1,VerF_FloA,JOMR_nov25_MBV_03
4,JOMR_nov25_MBV_03_p5,VerF_FloA,2,2,0,0,0,0,JOMR,JOMR_nov25_MBV_03
...,...,...,...,...,...,...,...,...,...,...
787,JOMR_oct25_SSA_05_p96,MaMeB_MarS,12,10,1,1,2,-2,MaMeB_MarS,JOMR_oct25_SSA_05
788,JOMR_oct25_SSA_05_p97,MaMeB_MarS,12,11,1,1,1,-1,JOMR,JOMR_oct25_SSA_05
789,JOMR_oct25_SSA_05_p98,JOMR,13,11,1,1,2,-2,MaMeB_MarS,JOMR_oct25_SSA_05
790,JOMR_oct25_SSA_05_p99,MaMeB_MarS,13,12,1,1,1,-1,JOMR,JOMR_oct25_SSA_05
791,JOMR_oct25_SSA_05_p100,JOMR,14,12,1,1,2,-2,JOMR,JOMR_oct25_SSA_05

In [2]:
action_graded = {
    'point_id': 'point n°2',
    'player': 'Jade',
    'action': 'serve',
    'grade': 'faute'
}
action_graded['action']

'serve'

In [4]:
indexed_dir = r'C:\Users\habib\Documents\GitHub\DataBeach\indexed_df_points'
import os
initial_string = str('Service_side,Start_frame,End_frame')
new_string = ''.join(ch.lower() if ch.isupper() else ch for ch in initial_string)
# print(new_string)

for file_name in os.listdir(indexed_dir):
    if file_name.lower().endswith('.csv'):
        file_path = os.path.join(indexed_dir, file_name)

        with open(file_path, 'r', encoding='utf-8', newline='') as f:
            lines = f.readlines()
        if lines:
            header = lines[0]
            if initial_string in header:
                lines[0] = header.replace(initial_string, new_string)
                with open(file_path, 'w', encoding='utf-8', newline='') as f:
                    f.writelines(lines)

In [1]:
from etl_utils import extract_transform_indexed_df_points_csv
test_df = extract_transform_indexed_df_points_csv(
    game_id='JOMR_jan26_MBV_01',
    team_a_name='JOMR',
    team_b_name='NoG_AliP'
    )
test_df.head()

,point_id,service_side,team_a_score,team_b_score,team_a_sets,team_b_sets,team_a_score_diff,team_b_score_diff,point_winner,game_id
0,JOMR_jan26_MBV_01_p1,NoG_AliP,0,0,0,0,0,0,JOMR,JOMR_jan26_MBV_01
1,JOMR_jan26_MBV_01_p2,JOMR,1,0,0,0,1,-1,NoG_AliP,JOMR_jan26_MBV_01
2,JOMR_jan26_MBV_01_p3,NoG_AliP,1,1,0,0,0,0,NoG_AliP,JOMR_jan26_MBV_01
3,JOMR_jan26_MBV_01_p4,NoG_AliP,1,2,0,0,-1,1,JOMR,JOMR_jan26_MBV_01
4,JOMR_jan26_MBV_01_p5,JOMR,2,2,0,0,0,0,NoG_AliP,JOMR_jan26_MBV_01

In [1]:
from db_manager import DBManager
import os
import json

file_path = r'C:\Users\habib\Documents\GitHub\DataBeach\actions_graded\list_grades_pass_JOMR_nov25_BSD_02.json'

with open(file_path, 'r') as f:
    actions_grades_list = json.load(f)

actions_grades_list
serve_or_pass = 'pass'

with DBManager() as db:
    db.cursor.execute(
        f"""CREATE TABLE IF NOT EXISTS table_{serve_or_pass} (
            action_id TEXT PRIMARY KEY AUTOINCREMENT,
            point_id TEXT,
            paire_id TEXT,
            player TEXT,
            action TEXT,
            grade TEXT,
            point_won BOOLEAN,
            UNIQUE(point_id, player, action)
        )"""
    )


    # for action_graded in actions_grades_list:
    #     db.cursor.execute(
    #         f"""INSERT INTO table_{serve_or_pass} 
    #         (point_id, paire_id, player, action, grade)
    #         VALUES (?, ?, ?, ?, ?)
    #         ON CONFLICT (POINT_ID) DO NOTHING""",
    #         (
    #             action_graded['point_id'],
    #             action_graded['paire_id'],
    #             action_graded['player'],
    #             action_graded['action'],
    #             action_graded['grade']
    #         )
    #     )

✅ Connexion établie : database/databeach_base.db
🔒 Connexion fermée.

In [4]:
import pprint
with DBManager() as db:
    db.execute_query("PRAGMA table_info(table_pass)")
    specs = db.cursor.fetchall()
pprint.pprint(specs)

✅ Connexion établie : database/databeach_base.db
✅ Requête exécutée avec succès.
🔒 Connexion fermée.
[(0, 'pass_id', 'INTEGER', 0, None, 1),
 (1, 'point_id', 'TEXT', 1, None, 0),
 (2, 'paire_id', 'TEXT', 1, None, 0),
 (3, 'player', 'TEXT', 1, None, 0),
 (4, 'action', 'TEXT', 1, None, 0),
 (5, 'grade', 'TEXT', 1, None, 0),
 (6, 'point_won', 'BOOLEAN', 0, None, 0),
 (7, 'created_at', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)]

In [36]:
with DBManager() as db:
    table_serve = db.table_to_dataframe('table_serve')
table_serve.head(2)

✅ Connexion établie : database/databeach_base.db
✅ Table 'table_serve' exportée : 144 lignes, 8 colonnes
🔒 Connexion fermée.

,serve_id,point_id,paire_id,player,action,grade,point_won,created_at
0,1,JOMR_jan26_MBV_01_p2,JOMR,RANC Mathilde,serve,out-of-system pass,None,2026-03-14 14:20:18
1,2,JOMR_jan26_MBV_01_p5,JOMR,OFFREDI Jade,serve,error,None,2026-03-14 14:20:18

In [37]:
from db_manager import DBManager

with DBManager() as db:
    table = db.table_to_dataframe('table_point')
table.head(2)

✅ Connexion établie : database/databeach_base.db
✅ Table 'table_point' exportée : 792 lignes, 10 colonnes
🔒 Connexion fermée.

,point_id,service_side,team_a_score,team_b_score,team_a_sets,team_b_sets,team_a_score_diff,team_b_score_diff,point_winner,game_id
0,JOMR_jan26_MBV_01_p1,NoG_AliP,0,0,0,0,0,0,JOMR,JOMR_jan26_MBV_01
1,JOMR_jan26_MBV_01_p2,JOMR,1,0,0,0,1,-1,NoG_AliP,JOMR_jan26_MBV_01

In [ ]:
with DBManager() as db:
    result = db.execute_query(
        """SELECT table_serve.point_id, table_serve.grade
        FROM table_serve
        INNER JOIN table_point ON table_serve.point_id = table_point.point_id
        WHERE table_point.point_winner = ?
        """,
        ("JOMR",)
    )

✅ Connexion établie : database/databeach_base.db
❌ Erreur lors de l'exécution de la requête: ambiguous column name: point_id
🔒 Connexion fermée.