In [1]:
from db_manager import DBManager
from game_editor import GameEditor
import pandas as pd

In [42]:
db = DBManager()
table_game = db.table_to_dataframe(table_name='table_game')
db.close()
table_game.head()

✅ Connexion établie : database/databeach_base.db
✅ Table 'table_game' exportée : 16 lignes, 12 colonnes
🔒 Connexion fermée.

,GAME_ID,serie,stage,teamA,teamB,victoire,set1_score,set2_score,set3_score,set1_score_adv,set2_score_adv,set3_score_adv
0,JOMR_jan26_MBV_01,MBV_S2-250_F_jan26,poule,JOMR,NoG_AliP,JOMR,,,,,,
1,JOMR_jan26_MBV_02,MBV_S2-250_F_jan26,poule,JOMR,AleN_EmP,JOMR,,,,,,
2,JOMR_jan26_MBV_03,MBV_S2-250_F_jan26,demi,JOMR,PauG_NeCH,JOMR,,,,,,
3,JOMR_jan26_MBV_04,MBV_S2-250_F_jan26,finale,JOMR,AleM_LauA,AleM_LauA,,,,,,
4,JOMR_nov24_Leuven_01,Leuven_Int_F_nov24,barrage,JOMR,(adv),(adv),,,,,,

In [ ]:
from db_manager import DBManager

serie_id = 'MBV_S2-250_F_jan26'
team_serving = 'JOMR'

with DBManager() as db:
    db.cursor.execute(
        f"""SELECT POINT_ID, Service_side 
        FROM table_points
        WHERE game_id IN
            (SELECT GAME_ID
            FROM table_game
            WHERE serie = ?)
        AND Service_side = ?""",
        (serie_id,team_serving)
    )
    
    POINTS_IDS = [row[0] for row in db.cursor.fetchall()]
    # print(f"POINTS_IDS for serie_id '{serie_id}' and team_serving '{team_serving}': {POINTS_IDS}")
    POUNTS_IDS_STR = ', '.join(map(str, POINTS_IDS))
    print(f"POINTS_IDS for serie_id '{serie_id}' and team_serving '{team_serving}': {POUNTS_IDS_STR}")

✅ Connexion établie : database/databeach_base.db
POINTS_IDS for serie_id 'MBV_S2-250_F_jan26' and team_serving 'JOMR': JOMR_jan26_MBV_01_p2, JOMR_jan26_MBV_01_p5, JOMR_jan26_MBV_01_p7, JOMR_jan26_MBV_01_p8, JOMR_jan26_MBV_01_p9, JOMR_jan26_MBV_01_p10, JOMR_jan26_MBV_01_p12, JOMR_jan26_MBV_01_p13, JOMR_jan26_MBV_01_p14, JOMR_jan26_MBV_01_p16, JOMR_jan26_MBV_01_p19, JOMR_jan26_MBV_01_p20, JOMR_jan26_MBV_01_p22, JOMR_jan26_MBV_01_p23, JOMR_jan26_MBV_01_p25, JOMR_jan26_MBV_01_p26, JOMR_jan26_MBV_01_p27, JOMR_jan26_MBV_01_p30, JOMR_jan26_MBV_01_p31, JOMR_jan26_MBV_01_p33, JOMR_jan26_MBV_02_p2, JOMR_jan26_MBV_02_p3, JOMR_jan26_MBV_02_p5, JOMR_jan26_MBV_02_p7, JOMR_jan26_MBV_02_p12, JOMR_jan26_MBV_02_p15, JOMR_jan26_MBV_02_p16, JOMR_jan26_MBV_02_p18, JOMR_jan26_MBV_02_p19, JOMR_jan26_MBV_02_p20, JOMR_jan26_MBV_02_p23, JOMR_jan26_MBV_02_p24, JOMR_jan26_MBV_02_p26, JOMR_jan26_MBV_02_p28, JOMR_jan26_MBV_02_p30, JOMR_jan26_MBV_02_p31, JOMR_jan26_MBV_02_p34, JOMR_jan26_MBV_03_p3, JOMR_jan26_MBV_03_p4, JOMR_jan26_MBV_03_p5, JOMR_jan26_MBV_03_p6, JOMR_jan26_MBV_03_p7, JOMR_jan26_MBV_03_p9, JOMR_jan26_MBV_03_p10, JOMR_jan26_MBV_03_p16, JOMR_jan26_MBV_03_p19, JOMR_jan26_MBV_03_p25, JOMR_jan26_MBV_03_p26, JOMR_jan26_MBV_03_p27, JOMR_jan26_MBV_03_p28, JOMR_jan26_MBV_03_p29, JOMR_jan26_MBV_03_p30, JOMR_jan26_MBV_03_p31, JOMR_jan26_MBV_03_p34, JOMR_jan26_MBV_03_p35, JOMR_jan26_MBV_03_p37, JOMR_jan26_MBV_03_p38, JOMR_jan26_MBV_03_p40, JOMR_jan26_MBV_03_p43, JOMR_jan26_MBV_03_p45, JOMR_jan26_MBV_03_p51, JOMR_jan26_MBV_03_p52, JOMR_jan26_MBV_03_p53, JOMR_jan26_MBV_03_p56, JOMR_jan26_MBV_03_p58, JOMR_jan26_MBV_03_p60, JOMR_jan26_MBV_03_p62, JOMR_jan26_MBV_03_p63, JOMR_jan26_MBV_03_p65, JOMR_jan26_MBV_03_p67, JOMR_jan26_MBV_03_p68, JOMR_jan26_MBV_03_p70, JOMR_jan26_MBV_04_p1, JOMR_jan26_MBV_04_p5, JOMR_jan26_MBV_04_p6, JOMR_jan26_MBV_04_p10, JOMR_jan26_MBV_04_p13, JOMR_jan26_MBV_04_p17, JOMR_jan26_MBV_04_p21, JOMR_jan26_MBV_04_p22, JOMR_jan26_MBV_04_p24, JOMR_jan26_MBV_04_p25, JOMR_jan26_MBV_04_p26, JOMR_jan26_MBV_04_p33, JOMR_jan26_MBV_04_p34, JOMR_jan26_MBV_04_p40, JOMR_jan26_MBV_04_p43
🔒 Connexion fermée.

In [4]:
paire_id = 'JOMR'
from db_manager import DBManager
db = DBManager()
db.cursor.execute(
    """SELECT Name_joueurA, Name_joueurB
    FROM table_players
    WHERE PAIRE_ID = ?""",
    (paire_id,)
)
result = db.cursor.fetchone()
if result: 
    player_a, player_b = result
    print(f"Player A: {player_a}, Player B: {player_b}")

from video_edit_utils import basic_action_grader

dict_b = basic_action_grader(
    video_path=r'C:\Users\habib\Desktop\Montages volley et beach\Jade&Math\matchs preprocess\points_segmented\JOMR_jan26_MBV_01_p1.mp4',
    player_a=player_a,
    player_b=player_b,
    action_to_grade='pass'
)

✅ Connexion établie : database/databeach_base.db
Player A: OFFREDI Jade, Player B: RANC Mathilde

In [5]:
dict_b

{'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'error'}

In [7]:
dict_a.update(dict_b)

In [12]:
import pandas
list_dict = [dict_a, dict_b]
df = pandas.DataFrame(list_dict)
df

          player action  grade
0  RANC Mathilde   pass  error
1  RANC Mathilde   pass  error

In [5]:
list_grades_BSD_02 = [{'point_id': 'JOMR_nov25_BSD_02_p2', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p6', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'undetermined'}, {'point_id': 'JOMR_nov25_BSD_02_p10', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p15', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p17', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p20', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'perfect pass'}, {'point_id': 'JOMR_nov25_BSD_02_p21', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p23', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p25', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'perfect pass'}, {'point_id': 'JOMR_nov25_BSD_02_p26', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'out-of-system pass'}, {'point_id': 'JOMR_nov25_BSD_02_p32', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'average pass'}, {'point_id': 'JOMR_nov25_BSD_02_p40', 'player': 'RANC Mathilde', 'action': 'pass', 'grade': 'error'}, {'point_id': 'JOMR_nov25_BSD_02_p41', 'player': 'OFFREDI Jade', 'action': 'pass', 'grade': 'average pass'}]

In [7]:
import json

with open('list_grades_BSD_02.json', 'w') as f:
    json.dump(list_grades_BSD_02, f, indent=2)

In [6]:
import pprint
import pandas
# pprint.pprint(list_grades)
df = pandas.DataFrame(list_grades_BSD_02)
df

                 point_id         player action               grade
0    JOMR_nov25_BSD_02_p2  RANC Mathilde   pass        average pass
1    JOMR_nov25_BSD_02_p6   OFFREDI Jade   pass        undetermined
2   JOMR_nov25_BSD_02_p10  RANC Mathilde   pass        average pass
3   JOMR_nov25_BSD_02_p15   OFFREDI Jade   pass        average pass
4   JOMR_nov25_BSD_02_p17   OFFREDI Jade   pass        average pass
5   JOMR_nov25_BSD_02_p20  RANC Mathilde   pass        perfect pass
6   JOMR_nov25_BSD_02_p21   OFFREDI Jade   pass        average pass
7   JOMR_nov25_BSD_02_p23   OFFREDI Jade   pass        average pass
8   JOMR_nov25_BSD_02_p25   OFFREDI Jade   pass        perfect pass
9   JOMR_nov25_BSD_02_p26   OFFREDI Jade   pass  out-of-system pass
10  JOMR_nov25_BSD_02_p32  RANC Mathilde   pass        average pass
11  JOMR_nov25_BSD_02_p40  RANC Mathilde   pass               error
12  JOMR_nov25_BSD_02_p41   OFFREDI Jade   pass        average pass